

package puntos;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


public class ejercicio4 extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
  
    public ejercicio4() {
        this.setContentPane(fondo);
        initComponents();
         this.setTitle("Ejerciocio #4");
        Bloquear();
       
        this.setMinimumSize(new Dimension(400, 400));
    }
    
    public void Bloquear() {
    
        for (Component a: jPanel2.getComponents()) {
            a.setEnabled(false);
        }
        
    }
    
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        Opcion1 = new javax.swing.JRadioButton();
        Opcion2 = new javax.swing.JRadioButton();
        Opcion3 = new javax.swing.JRadioButton();
        Opcion4 = new javax.swing.JCheckBox();
        Opcion5 = new javax.swing.JCheckBox();
        Opcion6 = new javax.swing.JCheckBox();
        TextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new FondoPanel();
        jLabel2 = new javax.swing.JLabel();
        Opcion2E = new javax.swing.JRadioButton();
        Opcion1E = new javax.swing.JRadioButton();
        Opcion3E = new javax.swing.JRadioButton();
        Opcion4E = new javax.swing.JCheckBox();
        Opcion6E = new javax.swing.JCheckBox();
        Opcion5E = new javax.swing.JCheckBox();
        TextField1E = new javax.swing.JTextField();
        jComboBox1E = new javax.swing.JComboBox<>();
        jSpinner1E = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ORIGINAL");

        buttonGroup1.add(Opcion1);
        Opcion1.setText("OPCION 1");
        Opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Opcion2);
        Opcion2.setText("OPCION 2");
        Opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Opcion3);
        Opcion3.setText("OPCION 3");
        Opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion3ActionPerformed(evt);
            }
        });

        Opcion4.setText("OPCION 4");
        Opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion4ActionPerformed(evt);
            }
        });

        Opcion5.setText("OPCION 5");
        Opcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion5ActionPerformed(evt);
            }
        });

        Opcion6.setText("OPCION 6");
        Opcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion6ActionPerformed(evt);
            }
        });

        TextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextField1MouseClicked(evt);
            }
        });
        TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField1ActionPerformed(evt);
            }
        });
        TextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField1KeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
        });
        jSpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinner1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Opcion1)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(Opcion4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Opcion2)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(Opcion5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Opcion3)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(Opcion6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextField1)
                        .addComponent(jComboBox1, 0, 114, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion1)
                    .addComponent(Opcion4)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion2)
                    .addComponent(Opcion5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion3)
                    .addComponent(Opcion6)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("ESPEJO");

        buttonGroup2.add(Opcion2E);
        Opcion2E.setText("OPCION 2");
        Opcion2E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion2EActionPerformed(evt);
            }
        });

        buttonGroup2.add(Opcion1E);
        Opcion1E.setText("OPCION 1");
        Opcion1E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion1EActionPerformed(evt);
            }
        });

        buttonGroup2.add(Opcion3E);
        Opcion3E.setText("OPCION 3");

        Opcion4E.setText("OPCION 4");
        Opcion4E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion4EActionPerformed(evt);
            }
        });

        Opcion6E.setText("OPCION 6");

        Opcion5E.setText("OPCION 5");

        TextField1E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextField1EMousePressed(evt);
            }
        });
        TextField1E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField1EActionPerformed(evt);
            }
        });
        TextField1E.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField1EKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField1EKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField1EKeyTyped(evt);
            }
        });

        jComboBox1E.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSpinner1E.setValue(jSpinner1.getValue());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Opcion1E)
                            .addGap(18, 18, 18)
                            .addComponent(Opcion4E))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Opcion2E)
                            .addGap(18, 18, 18)
                            .addComponent(Opcion5E))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Opcion3E)
                            .addGap(18, 18, 18)
                            .addComponent(Opcion6E)))
                    .addGap(44, 44, 44)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSpinner1E, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField1E)
                            .addComponent(jComboBox1E, 0, 114, Short.MAX_VALUE)))
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Opcion1E)
                        .addComponent(Opcion4E)
                        .addComponent(TextField1E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Opcion2E)
                        .addComponent(Opcion5E)
                        .addComponent(jComboBox1E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Opcion3E)
                        .addComponent(Opcion6E)
                        .addComponent(jSpinner1E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion2ActionPerformed
        if(Opcion2.isSelected()==true)
        {
           Opcion2E.setSelected(true);
        } else if (Opcion2.isSelected()==false)
        {
           Opcion2E.setSelected(false);
        }
        
    }//GEN-LAST:event_Opcion2ActionPerformed

    private void TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField1ActionPerformed
        
    }//GEN-LAST:event_TextField1ActionPerformed

    private void Opcion2EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion2EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion2EActionPerformed

    private void TextField1EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField1EActionPerformed
        
    }//GEN-LAST:event_TextField1EActionPerformed

    private void Opcion4EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion4EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion4EActionPerformed

    private void Opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion1ActionPerformed
        if(Opcion1.isSelected()==true)
        {
           Opcion1E.setSelected(true);
        } else if (Opcion1.isSelected()==false)
        {
           Opcion1E.setSelected(false);
        }
        
    }//GEN-LAST:event_Opcion1ActionPerformed

    private void Opcion1EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion1EActionPerformed
        
        
    }//GEN-LAST:event_Opcion1EActionPerformed

    private void Opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion3ActionPerformed
        if(Opcion3.isSelected()==true)
        {
           Opcion3E.setSelected(true);
        } else if (Opcion3.isSelected()==false)
        {
           Opcion3E.setSelected(false);
        }
        
    }//GEN-LAST:event_Opcion3ActionPerformed

    private void Opcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion4ActionPerformed
        if(Opcion4.isSelected()==true)
        {
           Opcion4E.setSelected(true);
        } else if (Opcion4.isSelected()==false)
        {
           Opcion4E.setSelected(false);
        }
    }//GEN-LAST:event_Opcion4ActionPerformed

    private void Opcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion5ActionPerformed
        if(Opcion5.isSelected()==true)
        {
           Opcion5E.setSelected(true);
        } else if (Opcion5.isSelected()==false)
        {
           Opcion5E.setSelected(false);
        }
    }//GEN-LAST:event_Opcion5ActionPerformed

    private void Opcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion6ActionPerformed
        if(Opcion6.isSelected()==true)
        {
           Opcion6E.setSelected(true);
        } else if (Opcion6.isSelected()==false)
        {
           Opcion6E.setSelected(false);
        }
    }//GEN-LAST:event_Opcion6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox1E.setSelectedItem(jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextField1MouseClicked
       
    }//GEN-LAST:event_TextField1MouseClicked

    private void TextField1EKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField1EKeyPressed
        
    }//GEN-LAST:event_TextField1EKeyPressed

    private void TextField1EKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField1EKeyReleased
       
    }//GEN-LAST:event_TextField1EKeyReleased

    private void TextField1EKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField1EKeyTyped
       
    }//GEN-LAST:event_TextField1EKeyTyped

    private void TextField1EMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextField1EMousePressed
        
    }//GEN-LAST:event_TextField1EMousePressed

    private void TextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField1KeyPressed
        
    }//GEN-LAST:event_TextField1KeyPressed

    private void jSpinner1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyPressed
       
    }//GEN-LAST:event_jSpinner1KeyPressed

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
        
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void TextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField1KeyReleased
        TextField1E.setText(TextField1.getText());
    }//GEN-LAST:event_TextField1KeyReleased

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        this.jSpinner1E.setValue((Integer)this.jSpinner1.getValue());
    }//GEN-LAST:event_jSpinner1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Opcion1;
    private javax.swing.JRadioButton Opcion1E;
    private javax.swing.JRadioButton Opcion2;
    private javax.swing.JRadioButton Opcion2E;
    private javax.swing.JRadioButton Opcion3;
    private javax.swing.JRadioButton Opcion3E;
    private javax.swing.JCheckBox Opcion4;
    private javax.swing.JCheckBox Opcion4E;
    private javax.swing.JCheckBox Opcion5;
    private javax.swing.JCheckBox Opcion5E;
    private javax.swing.JCheckBox Opcion6;
    private javax.swing.JCheckBox Opcion6E;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField1E;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox1E;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner1E;
    // End of variables declaration//GEN-END:variables

class FondoPanel extends JPanel 
    {

        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/img/fondo1.png")).getImage();
                                                                                                                                                                                                                                                                                                                       
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this); 
            
            setOpaque(false);
            
            super.paint(g);
        }

    }

}
